version: '3.9'

networks:
  laravel:

services:

  # server service built with image
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel


  # database service built with image
  mysql:
    image: mysql:5.7.22
    container_name: mysql                       #default image name for own need
    restart: unless-stopped
    tty: true                                     # for mysql shell inteface
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel


  # script service built locally with docker file
  php:
    build: 
      context: .               # directory to check for our build . means same directory
      dockerfile: Dockerfile    # docker file for the php build
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
